# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboserv_description/Sensores.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sensores(genpy.Message):
  _md5sum = "4e7e993f2ad894e38becbb76ebb5ec09"
  _type = "roboserv_description/Sensores"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 SensorL
float32 SensorFL
float32 SensorF
float32 SensorFR
float32 SensorR
"""
  __slots__ = ['SensorL','SensorFL','SensorF','SensorFR','SensorR']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       SensorL,SensorFL,SensorF,SensorFR,SensorR

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sensores, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.SensorL is None:
        self.SensorL = 0.
      if self.SensorFL is None:
        self.SensorFL = 0.
      if self.SensorF is None:
        self.SensorF = 0.
      if self.SensorFR is None:
        self.SensorFR = 0.
      if self.SensorR is None:
        self.SensorR = 0.
    else:
      self.SensorL = 0.
      self.SensorFL = 0.
      self.SensorF = 0.
      self.SensorFR = 0.
      self.SensorR = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.SensorL, _x.SensorFL, _x.SensorF, _x.SensorFR, _x.SensorR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.SensorL, _x.SensorFL, _x.SensorF, _x.SensorFR, _x.SensorR,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.SensorL, _x.SensorFL, _x.SensorF, _x.SensorFR, _x.SensorR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.SensorL, _x.SensorFL, _x.SensorF, _x.SensorFR, _x.SensorR,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
