<?xml version="1.0"?>
<robot>


	<!--Criando um cilindro-->
	<macro name="create_cylinder" params="name mass radius length px py pz wr wp wy">
		<collision name="${name}_collision">
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<geometry>
				<cylinder radius="${radius}" length="${length}"/>
			</geometry>
		</collision>
		<visual name="${name}_visual">
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<geometry>
				<cylinder radius="${radius}" length="${length}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<mass value="${mass}"/>
			<inertia  
				ixx="${mass*(3*radius*radius+length*length)/12}" ixy = "0" ixz = "0"
				iyy="${mass*(3*radius*radius+length*length)/12}" iyz = "0"
				izz="${mass*radius*radius/2}" />
		</inertial>
	</macro>
	
	<!--Criando uma caixa-->
	<macro name="create_box" params="name mass size_x size_y size_z px py pz wr wp wy">
		<collision name="${name}_collision">
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<geometry>
				<box size="${size_x} ${size_y} ${size_z}"/>
			</geometry>
		</collision>
		<visual name="${name}_visual">
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<geometry>
				<box size="${size_x} ${size_y} ${size_z}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz = "${px} ${py} ${pz+0.1}" rpy="${wr} ${wp} ${wy}"/>
			<mass value="${mass}"/>
			<inertia
				ixx="${mass*(size_y*size_y+size_z*size_z)/12}" ixy = "0" ixz = "0"
				iyy="${mass*(size_x*size_x+size_z*size_z)/12}" iyz = "0"
				izz="${mass*(size_x*size_x+size_z*size_z)/12}" />
		</inertial>
	</macro>
	
	<!--Criando uma esfera-->
	<macro name="create_sphere" params="name mass radius px py pz wr wp wy">
		<collision name="${name}_collision">
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<geometry>
				<sphere radius="${radius}"/>
			</geometry>
			<surface>
				<friction>
					<ode>
						<mu>0</mu>
						<mu2>0</mu2>
						<slip1>1.0</slip1>
						<slip2>1.0</slip2>
					</ode>
				</friction>
			</surface>
		</collision>
		<visual name="${name}_visual">
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<geometry>
				<sphere radius="${radius}"/>
			</geometry>
		</visual>
		<inertial>
			<origin xyz = "${px} ${py} ${pz}" rpy="${wr} ${wp} ${wy}"/>
			<mass value="${mass}"/>
			<inertia  
				ixx="${mass*radius*radius*2/5}" ixy = "0" ixz = "0"
				iyy="${mass*radius*radius*2/5}" iyz = "0"
				izz="${mass*radius*radius*2/5}" />
		</inertial>
	</macro>

	<!--Criando uma roda-->
	<macro name="create_wheel" params="name mass radius length body_name body_size_x body_size_y wheel_pos_x wheel_side whell_spacing">
		
		<!--Cria um cilindro-->
		<link name="${name}">
			<create_cylinder name="${name}" mass="${mass}" radius="${radius}" length="${length}"
						  px="0" py="0" pz="0" wr="0" wp="${pi/2}" wy="${pi/2}"/>
		</link>
		
		<!--Cria uma referencia no Gazebo-->
		<gazebo reference="${name}">
			<mu1 value="1.0"/>
			<mu2 value="1.0"/>
			<kp  value="1000000.0" />
			<kd  value="100.0" />
			<max_vel value="1.0" />
			<fdir1 value="0 0 0"/>
			<material>Gazebo/Black</material>
		</gazebo>
		
		<!--Cria a juncao com o corpo-->
		<joint name="${name}_hinge" type="continuous">
			<parent link="${body_name}"/>
			<child link="${name}"/>
			<origin xyz="${-wheel_pos_x+body_size_x/2} ${(length/2+body_size_y/2+whell_spacing)*wheel_side} 0" rpy="0 0 0" />
			<axis xyz="0 1 0" rpy="0 0 0" />
			<limit effort="10000" velocity="10000"/>
			<joint_properties damping="1.0" friction="1.0"/>
		</joint>
		
		<!--Cria uma configuracao de transmissao-->
		<transmission name="${name}_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${name}_hinge">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="${name}_motor">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>10</mechanicalReduction>
			</actuator>
		</transmission>
		
	</macro>
	
</robot>