# footprint: [[-0.2,  -0.2], [-0.2,   0.2], [0.2,    0.2], [0.2,   -0.2]]

footprint: [
    [-0.35,  0.05], 
    [-0.1,  0.25], 
    [0.1,   0.25], 
    [0.25,  0.1], 
    [0.25,  -0.1], 
    [0.1,   -0.25], 
    [-0.1,  -0.25], 
    [-0.35,  -0.05]]

footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.0
raytrace_range: 4.0

