global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}


#layer definitions
static:
    map_topic: /map
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    subscribe_to_updates: true