# footprint: [[-0.2,  -0.2], [-0.2,   0.2], [0.2,    0.2], [0.2,   -0.2]]

footprint: [
    [-0.35,  0.05], 
    [-0.1,  0.25], 
    [0.1,   0.25], 
    [0.25,  0.1], 
    [0.25,  -0.1], 
    [0.1,   -0.25], 
    [-0.1,  -0.25], 
    [-0.35,  -0.05]]

#footprint: [[-0.69, 0.1], [-0.2, 0.49], [0.2, 0.49], [0.49, 0.2], [0.49, -0.2], [0.2, -0.49], [-0.2, -0.49], [-0.69, -0.1]]

footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5
publish_frequency: 5
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.0
raytrace_range: 4.0

#layer definitions
static:
    map_topic: /map
    unknown_cost_value: -5
    lethal_cost_threshold: -2
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.25
